
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


CREATE TABLE IF NOT EXISTS `USUARIO` (
  `IDUSUARIO` int(11) NOT NULL,
  `NOME` varchar(20) NOT NULL,
  `USUARIO` varchar(200) NOT NULL,
  `SENHA` varchar(100) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;


INSERT INTO `USUARIO` (`IDUSUARIO`, `NOME`, `USUARIO`, `SENHA`) VALUES
(1, 'Fernando Humel', 'fernando', '');


CREATE TABLE IF NOT EXISTS `MENSAGEM` (
  `IDMENSAGEM` int(11) NOT NULL,
  `NOME` varchar(255) NOT NULL,
  `TELEFONE` varchar(255) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `MENSAGEM` varchar(255) NOT NULL,
  `DATA` timestamp NOT NULL,
  `STATUS` varchar(255) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;



INSERT INTO `MENSAGEM` (`IDMENSAGEM`,`NOME`,`TELEFONE`,`EMAIL`,`MENSAGEM`,`DATA`,`STATUS`) VALUES
(1, 'Fernando Humel', '4487-0349', 'fhumel@hotmail.com', 'Como está a mensagem?', '2010-07-23 14:15:31', 'pendente');


CREATE TABLE IF NOT EXISTS `IMOVEL` (
  `IDIMOVEL` int(11) NOT NULL,
  `IMOVELTITULO` varchar(255) NOT NULL,
  `IMOVELNOME` varchar(255) NOT NULL,
  `IMOVELCATEGORIA` varchar(255) NOT NULL,
  `IMOVELVALOR` varchar(255) NULL,
  `IMOVELDESCRICAO` varchar(255) NULL,
  `IMOVELCOMODOS` varchar(255) NULL,
  `IMOVELSUITES` varchar(255) NULL,
  `IMOVELBANHEIROS` varchar(255) NULL,
  `IMOVELSALAS` varchar(255) NULL,
  `IMOVELCHURRASQUEIRA` varchar(255) NULL,
  `IMOVELGARAGEM` varchar(255) NULL,
  `IMOVELSERVICO` varchar(255) NULL,
  `IMOVELPISCINA` varchar(255) NULL,
  `NOVIDADES` varchar(255) NULL,
  `IMOVELRUA` varchar(255) NULL,
  `IMOVELBAIRRO` varchar(255) NULL,
  `IMOVELCIDADE` varchar(255) NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `FOTO` (
  `IDFOTO` int(11) NOT NULL,
  `FOTONOME` varchar(255) NOT NULL,
  `IDIMOVEL` int(11) NOT NULL
  
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;



ALTER TABLE `USUARIO`
  ADD PRIMARY KEY (`IDUSUARIO`);

ALTER TABLE `MENSAGEM`
  ADD PRIMARY KEY (`IDMENSAGEM`);


ALTER TABLE `IMOVEL`
  ADD PRIMARY KEY (`IDIMOVEL`);

	
ALTER TABLE `FOTO`
  ADD PRIMARY KEY (`IDFOTO`),
    ADD KEY `FK_IMOVEL` (`IDIMOVEL`);


ALTER TABLE `MENSAGEM`
  MODIFY `IDMENSAGEM` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;

  
ALTER TABLE `USUARIO`
  MODIFY `IDUSUARIO` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;

ALTER TABLE `IMOVEL`
  MODIFY `IDIMOVEL` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;

ALTER TABLE `FOTO`
  MODIFY `IDFOTO` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;

  


ALTER TABLE `FOTO`
 ADD CONSTRAINT `FK_IMOVEL` FOREIGN KEY (`IDIMOVEL`) REFERENCES `IMOVEL` (`IDIMOVEL`) ON DELETE CASCADE ON UPDATE CASCADE;

